### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by mangel8** [ioBroker/ioBroker.lcn#1]
After installation from git when i want to configure the instance i cant open the config pahe it only shows.
File index_m.html not found
Thank you for your help

Solved
When you use the repository  in the admin adapter http://download.iobroker.net/sources-dist-latest.json you can install the instance inside of ioBroker and it runs fine

**Comment by tonischabloni** [comment]
Hi,
have the same issue with missing index_m.htmtl after adding instance to IOBroker.
When you click on setup button the error message appears.
thx for your support!
