### ISSUE TITLE
Read Buttons A-D 

### ISSUE THREAD

**Issue by mangel8** [ioBroker/ioBroker.lcn#14]
Hallo es wäre super wenn man die Tasten aus den Tabellen A-D in den Modulen auch im ioBroker zur Steuerung verwenden könnte.
Wäre das möglich einzubauen?
Danke und Grüße
Michael

**Comment by MatthiasUlrich84** [comment]
Hallo Michael,
Das wird nicht funktionieren, da LCN keine Tastenbefehle sendet, sondern nur Zielbefehle. Das heißt gedrückte Tasten sind nicht auslesbar. Sie senden nur beim drücken das im Modul hinterlegte Ziel-Telegramm. 

Gruß Matthias

**Comment by MatthiasUlrich84** [comment]
Es gibt wohl die Funktion sende Kommando an Host in der PCK Doku die Doku liegt mir auch vor. Aber ob das implementiert werden kann in diesen Adapter da bin ich überfragt. Das ist auch eigentlich nicht vorgesehen für den Standardanwender.
