### ISSUE TITLE
Adapter möchte auf Segment 4 zugreifen

### ISSUE THREAD

**Issue by mangel8** [ioBroker/ioBroker.lcn#17]
Hallo. Ich habe schon seit längerem Probleme mit diversen Modulen. Sie werden beim Scan nicht vollständig erkannt. Also es fehlen Ausgänge oder Variablen. Wenn ich dann in die Logs schaue sehe ich das die fehlenden Objekte versucht werden anzulegen aber es leider rutscht da irgendwie das Segment 4 mit rein. Komisch ist auch das es immer bei den selben modulen der Fall ist und auch eine Neuinstallation des Adapters bringt keine veränderung. Hier der Scan des Moduls 14 einmal aus dem Busmonitor der LCN-Pro und einmal alle fehlerhaften Module aus dem IOBroker log.
Bin etwas ratlos am Anfang war nur ein Modul betroffen mitterweile 4  von 48

13:31:24:148 - M014 E 05 B1   Var2/R1Var: 1208
13:31:24:208 - M014 E 05 B1   Var3/R2Var: 1176
13:31:24:456 - M014 E 05 B1   Variable 4: 1176
13:31:25:329 - M014 E 05 B1   Regler 1: Sollwertquelle ist jetzt "Regler Sollwert"
13:31:25:455 - M014 E 05 B1   Regler 1 Sollwert: 1230
13:31:25:545 - M014 E 05 B1   Regler 2: Sollwertquelle ist jetzt "Regler Sollwert"
13:31:25:664 - M014 E 05 B1   Regler 2 Sollwert: ---
13:31:25:913 - M014 E 05 B1   Relais: 0 0 0 0  0 0 0 0
13:31:26:037 - M014 E 05 B1   Ausg.1: 0.0%
13:31:26:161 - M014 E 05 B1   Ausg.2: 0.0%
13:31:26:348 - M014 E 05 B1   Ausg.3: 0.0%
13:31:26:536 - M014 E 05 B1   Ausg.4: 100.0%

lcn.0 | 2022-01-18 13:24:27.211 | info | Found total 1 modules. New 0
lcn.0 | 2022-01-18 13:24:27.098 | info | [LCN] Scan finished. Found 1 modules
lcn.0 | 2022-01-18 13:24:24.341 | error | Cannot read object lcn.0.S004.M014.ANALOGS.ANALOG04: Not found
lcn.0 | 2022-01-18 13:24:24.197 | error | Cannot read object lcn.0.S004.M014.ANALOGS.ANALOG03: Not found
lcn.0 | 2022-01-18 13:24:24.064 | error | Cannot read object lcn.0.S004.M014.ANALOGS.ANALOG02: Not found
lcn.0 | 2022-01-18 13:24:23.334 | warn | [LCN] unknown data received: :M004014??255
lcn.0 | 2022-01-18 13:24:23.201 | warn | [LCN] unknown data received: :M004014??255
lcn.0 | 2022-01-18 13:24:22.937 | error | Cannot read object lcn.0.S004.M014.VARS.VAR04: Not found
lcn.0 | 2022-01-18 13:24:22.894 | error | Cannot read object lcn.0.S004.M014.VARS.VAR03: Not found
lcn.0 | 2022-01-18 13:24:22.861 | error | Cannot read object lcn.0.S004.M014.VARS.VAR02: Not found

lcn.0 | 2022-01-18 13:35:21.053 | info | Found total 1 modules. New 0
lcn.0 | 2022-01-18 13:35:20.940 | info | [LCN] Scan finished. Found 1 modules
lcn.0 | 2022-01-18 13:35:18.241 | error | Cannot read object lcn.0.S004.M020.ANALOGS.ANALOG04: Not found
lcn.0 | 2022-01-18 13:35:18.017 | error | Cannot read object lcn.0.S004.M020.ANALOGS.ANALOG03: Not found
lcn.0 | 2022-01-18 13:35:17.884 | error | Cannot read object lcn.0.S004.M020.ANALOGS.ANALOG02: Not found
lcn.0 | 2022-01-18 13:35:17.242 | warn | [LCN] unknown data received: :M004020??255
lcn.0 | 2022-01-18 13:35:17.017 | warn | [LCN] unknown data received: :M004020??255

lcn.0 | 2022-01-18 13:38:23.727 | info | Found total 1 modules. New 0
lcn.0 | 2022-01-18 13:38:23.616 | info | [LCN] Scan finished. Found 1 modules
lcn.0 | 2022-01-18 13:38:20.918 | error | Cannot read object lcn.0.S004.M011.ANALOGS.ANALOG04: Not found
lcn.0 | 2022-01-18 13:38:20.783 | error | Cannot read object lcn.0.S004.M011.ANALOGS.ANALOG03: Not found
lcn.0 | 2022-01-18 13:38:20.619 | error | Cannot read object lcn.0.S004.M011.ANALOGS.ANALOG02: Not found
lcn.0 | 2022-01-18 13:38:19.779 | warn | [LCN] unknown data received: :M004011??255
lcn.0 | 2022-01-18 13:38:19.613 | warn | [LCN] unknown data received: :M004011??255
lcn.0 | 2022-01-18 13:37:27.249 | error | Cannot read object lcn.0.S004.M014.VARS.VAR04: Not found
lcn.0 | 2022-01-18 13:36:58.882 | warn | [LCN] unknown data received: :M000013??255

lcn.0 | 2022-01-18 13:39:40.328 | info | Found total 1 modules. New 0
lcn.0 | 2022-01-18 13:39:40.205 | info | [LCN] Scan finished. Found 1 modules
lcn.0 | 2022-01-18 13:39:37.508 | error | Cannot read object lcn.0.S004.M035.ANALOGS.ANALOG04: Not found
lcn.0 | 2022-01-18 13:39:37.281 | error | Cannot read object lcn.0.S004.M035.ANALOGS.ANALOG03: Not found
lcn.0 | 2022-01-18 13:39:37.147 | error | Cannot read object lcn.0.S004.M035.ANALOGS.ANALOG02: Not found
lcn.0 | 2022-01-18 13:39:36.645 | warn | [LCN] unknown data received: :M004035??255
lcn.0 | 2022-01-18 13:39:36.498 | warn | [LCN] unknown data received: :M004035??255

**Comment by mangel8** [comment]
Ok ich habe mich jetzt wirklich seit über einem Jahr mit dem Problem rumgeschlagen und schon lösungen drum rum gebastelt.
Jetzt habe ich es geschafft den Fehler zu reproduzieren bzw. auf andere Module auszuweiten.
Das ganze passiert nur wenn man in der LCN-Pro in den Moduleigenschaften unter erweitert irgendetwas anderes als das
![grafik](https://user-images.githubusercontent.com/46531142/149948555-6fd90fd6-a7bc-4220-9c84-25e495250ddf.png)
einstellt. Warum auch immer es ist so.

**Comment by MatthiasUlrich84** [comment]
Hey Mangel8 das ist interessant das werde ich mal testen. Kannst du mir sagen wie alt deine Module sind? 

Gruß Matthias

**Comment by mangel8** [comment]
Hallo Matthias,
die Module sind alle samt recht neu und wurden zusammen im Frühjahr 2021 angeschafft. FW 1F0302 und ähnliche.
Beobachtet bei UPP umd UMR sowie SH+ und LD.

Grüße Michael
