### ISSUE TITLE
Connection Password can't be saved in Admin 6

### ISSUE THREAD

**Issue by MatthiasUlrich84** [ioBroker/ioBroker.lcn#19]
If I use Admin 6 it is not possible to save the Setup if I fill in the LCN Connection Password.

**Comment by Apollon77** [comment]
Admin6 on the local host or via "pro cloud"?

**Comment by MatthiasUlrich84** [comment]
On the local host. If I want to configurate the Instance Setup for the connection zu the LCN PCHK I can‘t hit save if I fill in the Passwords for the Connection.

**Comment by Apollon77** [comment]
Ok, As workaround try to change any other field and change it back, that could unlock the save button

**Comment by MatthiasUlrich84** [comment]
I will try today in the evening and come back with feedback. Thank you!

**Comment by MatthiasUlrich84** [comment]
it works now
