### ISSUE TITLE
Modul 5 fragt Segment 4 ab, obwohl es nur ein Segment (0) gibt.

### ISSUE THREAD

**Issue by MatthiasUlrich84** [ioBroker/ioBroker.lcn#21]
Modul 5 fragt Segment 4 ab, obwohl es nur ein Segment (0) gibt. Daher wird vom Modul kein Status zurückgegeben.

Die Parameter der Objekte stimmen, dort steht überall Segment 0 drin. 
Woran könnte das liegen? 

Auch die Objekte werden nicht alle richtig angelegt. 

Bei Bedarf kann ich auch Zugang zum Rechner organisieren um das Problem zu analysieren.

![Screenshot 2023-01-15 143920](https://user-images.githubusercontent.com/56859840/212544111-d6e20de8-d3f7-4813-8fc4-7a9def992561.png)

**Comment by mangel8** [comment]
Hallo Matthias, hatte das selbe problem auch mal mit zwei Modulen, Hab dan aus verdacht mal das Modul getauscht da ich noch welche in der Kiste liegen hatte die nicht verbaut wahen und das Problem war weg. Im nachgang habe ich herausgefunden woran es bei mir lag. Ich hatte in der LCN Pro die Module unter eigenschaften auf "Meldung global" gestellt. Das hat bei mir reproduzierbar zu dem fehler geführt.
![grafik](https://user-images.githubusercontent.com/46531142/217628233-871394a2-ad0f-462f-abaa-9d76689ac0b9.png)

**Comment by MatthiasUlrich84** [comment]
Das war es tatsächlich. Danke! Das löst dieses Problem. 

Großartig!
