### ISSUE TITLE
Instalationsprobleme des Adapters

### ISSUE THREAD

**Issue by MatthiasUlrich84** [ioBroker/ioBroker.lcn#23]
Ich musste meinen Server neu aufsetzen wegen eines Hardwareausfalls.
Seit dem bekomme ich den LCN Adapter nicht mehr ans laufen.

Weder auf WIndows noch auf linux.
Es baut sich einfach keine Verbindung mehr auf.

Auf einer älteren Installation bekomme ich den Adapter zum laufen auch mit dem aktualisierten Adapter 1.1.1
Aber als neuinstallation funktioniert es nicht.

Ich benötige Hilfe

**Comment by Apollon77** [comment]
Bitte mehr Details liefern und auch Infos aus dem Log. Was ist denn die Ausgabe?

**Comment by MatthiasUlrich84** [comment]
Danke für die schnelle Antwort.

der ioBroker läuft auf Linux im Docker und wurde mit einer Backupdatei wiederhergsestellt:

LOG der Adapterninstallation:
$ iobroker add lcn auto --host cb9df8b82849 --debug

Installing iobroker.lcn@1.1.1... (System call)

added 1 package in 3s112 packages are looking for funding run `npm fund` for details

host.cb9df8b82849 install adapter lcn

upload [17] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/25.png icons/25.png image/png

upload [16] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/BEGA-EB2.png icons/BEGA-EB2.png image/png

upload [15] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-DI12.png icons/CMDS-DI12.png image/png

upload [14] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-ESD.png icons/CMDS-ESD.png image/png

upload [13] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-HU.png icons/CMDS-HU.png image/png

upload [12] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-SH.png icons/CMDS-SH.png image/png

upload [11] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-SHS.png icons/CMDS-SHS.png image/png

upload [10] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-SHplus.png icons/CMDS-SHplus.png image/png

upload [9] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-SK.png icons/CMDS-SK.png image/png

upload [8] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-UP.png icons/CMDS-UP.png image/png

upload [7] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-UP24.png icons/CMDS-UP24.png image/png

upload [6] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-UPP.png icons/CMDS-UPP.png image/png

upload [5] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS-UPS.png icons/CMDS-UPS.png image/png

upload [4] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/CMDS_LD.png icons/CMDS_LD.png image/png

upload [3] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/icons/IOS-GTM.png icons/IOS-GTM.png image/png

upload [2] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/index_m.html index_m.html text/html

upload [1] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/lcn.png lcn.png image/png

upload [0] lcn.admin /opt/iobroker/node_modules/iobroker.lcn/admin/words.js words.js application/javascript

host.cb9df8b82849 object system.adapter.lcn created/updated

host.cb9df8b82849 object system.adapter.lcn.0.cpu created

host.cb9df8b82849 object system.adapter.lcn.0.cputime created

host.cb9df8b82849 object system.adapter.lcn.0.memHeapUsed created

host.cb9df8b82849 object system.adapter.lcn.0.memHeapTotal created

host.cb9df8b82849 object system.adapter.lcn.0.memRss created

host.cb9df8b82849 object system.adapter.lcn.0.uptime created

host.cb9df8b82849 object system.adapter.lcn.0.inputCount created

host.cb9df8b82849 object system.adapter.lcn.0.outputCount created

host.cb9df8b82849 object system.adapter.lcn.0.eventLoopLag created

host.cb9df8b82849 object system.adapter.lcn.0.sigKill created

host.cb9df8b82849 object system.adapter.lcn.0.logLevel created

host.cb9df8b82849 object lcn.0.info created

host.cb9df8b82849 object lcn.0.info.connection created

host.cb9df8b82849 object lcn.0.scan created

host.cb9df8b82849 object lcn.0.scan.progress created

host.cb9df8b82849 object lcn.0.scan.found created

host.cb9df8b82849 object lcn.0.scan.manual created

host.cb9df8b82849 object lcn.0.ir created

host.cb9df8b82849 object lcn.0.ir.serial created

host.cb9df8b82849 object lcn.0.ir.key created

host.cb9df8b82849 object lcn.0.ir.lowbat created

host.cb9df8b82849 object lcn.0.ir.action created

host.cb9df8b82849 object lcn.0.finger created

host.cb9df8b82849 object lcn.0.finger.code created

host.cb9df8b82849 Set default value of lcn.0.info.connection: false

host.cb9df8b82849 object system.adapter.lcn.0 created

Process exited with code 0


Nach der neuinsatllation und Einstellung der Insatanz habe ich auf Debug modus umgestellt

Dann kam folgender log:

<html><body>


lcn.0 | 2023-02-02 05:34:13.401 | info | Found license with 20000 modules
-- | -- | -- | --
lcn.0 | 2023-02-02 05:34:13.275 | debug | [main] start
lcn.0 | 2023-02-02 05:34:13.257 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.lcn, node: v16.19.0, js-controller: 4.0.24
lcn.0 | 2023-02-02 05:34:13.120 | debug | States connected to redis: 127.0.0.1:9020
lcn.0 | 2023-02-02 05:34:13.064 | debug | States create User PubSub Client
lcn.0 | 2023-02-02 05:34:13.064 | debug | States create System PubSub Client
lcn.0 | 2023-02-02 05:34:13.055 | debug | Redis States: Use Redis connection: 127.0.0.1:9020
lcn.0 | 2023-02-02 05:34:13.031 | debug | Objects connected to redis: 127.0.0.1:9021
lcn.0 | 2023-02-02 05:34:13.011 | debug | Objects client initialize lua scripts
lcn.0 | 2023-02-02 05:34:12.980 | debug | Objects create User PubSub Client
lcn.0 | 2023-02-02 05:34:12.980 | debug | Objects create System PubSub Client
lcn.0 | 2023-02-02 05:34:12.979 | debug | Objects client ready ... initialize now
lcn.0 | 2023-02-02 05:34:12.948 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9021
lcn.0 | 2023-02-02 05:34:09.895 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
lcn.0 | 2023-02-02 05:34:09.895 | info | terminating
lcn.0 | 2023-02-02 05:34:09.393 | info | Got terminate signal TERMINATE_YOURSELF
lcn.0 | 2023-02-02 05:33:39.834 | info | Found license with 20000 modules
lcn.0 | 2023-02-02 05:33:39.680 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.lcn, node: v16.19.0, js-controller: 4.0.24


</body>
</html>

Adapter bleibt gelb (Dreieck )

![image](https://user-images.githubusercontent.com/56859840/216232726-29a28144-db2d-4395-959b-d98f9fbcc17b.png)

**Comment by MatthiasUlrich84** [comment]
Ich denke inzwischen, dass die Installation des Adapers einen fehler hat.

**Comment by MatthiasUlrich84** [comment]
Ich hab jetzt noch einmal direkt auf Linux den iobroker installiert.
Nun geht wird der Adapter auf grün und hat auch mal eine Verbindung. Im PCHK Monitor wird auch ein verbundener Client angezeigt.  Jedoch bricht die Verbindung ab mit folgendem LOG

<html><body>


lcn.0 | 2023-02-02 20:23:23.800 | debug | Command sent
-- | -- | -- | --
lcn.0 | 2023-02-02 20:23:23.799 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:23.599 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:23.598 | debug | Command sent
lcn.0 | 2023-02-02 20:23:23.598 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:23.397 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:23.397 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:23.197 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:23.196 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:22.995 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:22.995 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:22.994 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:22.993 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:22.992 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:22.991 | debug | [CONN] Changing state: WAIT_CONNECTED => READY
lcn.0 | 2023-02-02 20:23:16.787 | debug | [CONN] Changing state: READY => WAIT_CONNECTED
lcn.0 | 2023-02-02 20:23:14.126 | info | Create state lcn.0.S000.M211.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.122 | info | Create state lcn.0.S000.M211.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.120 | info | Create state lcn.0.S000.M211.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.116 | info | Create state lcn.0.S000.M211.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.113 | info | Create state lcn.0.S000.M211.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.109 | info | Create state lcn.0.S000.M211.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.105 | info | Create state lcn.0.S000.M210.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.097 | info | Create state lcn.0.S000.M210.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.093 | info | Create state lcn.0.S000.M210.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.091 | info | Create state lcn.0.S000.M210.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.089 | info | Create state lcn.0.S000.M210.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.088 | info | Create state lcn.0.S000.M210.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.085 | info | Create state lcn.0.S000.M202.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.083 | info | Create state lcn.0.S000.M202.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.081 | info | Create state lcn.0.S000.M202.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.079 | info | Create state lcn.0.S000.M202.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.077 | info | Create state lcn.0.S000.M202.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.075 | info | Create state lcn.0.S000.M202.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.072 | info | Create state lcn.0.S000.M201.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.068 | info | Create state lcn.0.S000.M201.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.065 | info | Create state lcn.0.S000.M201.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.062 | info | Create state lcn.0.S000.M201.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.057 | info | Create state lcn.0.S000.M201.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.052 | info | Create state lcn.0.S000.M201.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.048 | info | Create state lcn.0.S000.M201.RELAYS
lcn.0 | 2023-02-02 20:23:14.044 | info | Create state lcn.0.S000.M101.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.040 | info | Create state lcn.0.S000.M101.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.034 | info | Create state lcn.0.S000.M101.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.031 | info | Create state lcn.0.S000.M101.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.029 | info | Create state lcn.0.S000.M101.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.027 | info | Create state lcn.0.S000.M101.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.024 | info | Create state lcn.0.S000.M090.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.022 | info | Create state lcn.0.S000.M090.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:14.020 | info | Create state lcn.0.S000.M090.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:14.018 | info | Create state lcn.0.S000.M090.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:14.015 | info | Create state lcn.0.S000.M090.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:14.013 | info | Create state lcn.0.S000.M090.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:14.006 | info | Create state lcn.0.S000.M085.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:14.002 | info | Create state lcn.0.S000.M085.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.998 | info | Create state lcn.0.S000.M085.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.994 | info | Create state lcn.0.S000.M085.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.990 | info | Create state lcn.0.S000.M085.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.987 | info | Create state lcn.0.S000.M085.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.982 | info | Create state lcn.0.S000.M085.RELAYS
lcn.0 | 2023-02-02 20:23:13.978 | info | Create state lcn.0.S000.M080.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.974 | info | Create state lcn.0.S000.M080.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.970 | info | Create state lcn.0.S000.M080.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.966 | info | Create state lcn.0.S000.M080.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.962 | info | Create state lcn.0.S000.M080.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.959 | info | Create state lcn.0.S000.M080.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.952 | info | Create state lcn.0.S000.M040.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.949 | info | Create state lcn.0.S000.M040.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.947 | info | Create state lcn.0.S000.M040.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.944 | info | Create state lcn.0.S000.M040.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.942 | info | Create state lcn.0.S000.M040.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.940 | info | Create state lcn.0.S000.M040.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.938 | info | Create state lcn.0.S000.M035.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.935 | info | Create state lcn.0.S000.M035.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.931 | info | Create state lcn.0.S000.M035.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.929 | info | Create state lcn.0.S000.M035.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.926 | info | Create state lcn.0.S000.M035.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.924 | info | Create state lcn.0.S000.M035.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.921 | info | Create state lcn.0.S000.M030.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.918 | info | Create state lcn.0.S000.M030.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.907 | info | Create state lcn.0.S000.M030.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.905 | info | Create state lcn.0.S000.M030.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.902 | info | Create state lcn.0.S000.M030.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.900 | info | Create state lcn.0.S000.M030.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.896 | info | Create state lcn.0.S000.M030.RELAYS
lcn.0 | 2023-02-02 20:23:13.894 | info | Create state lcn.0.S000.M025.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.891 | info | Create state lcn.0.S000.M025.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.889 | info | Create state lcn.0.S000.M025.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.887 | info | Create state lcn.0.S000.M025.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.885 | info | Create state lcn.0.S000.M025.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.883 | info | Create state lcn.0.S000.M025.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.880 | info | Create state lcn.0.S000.M020.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.878 | info | Create state lcn.0.S000.M020.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.876 | info | Create state lcn.0.S000.M020.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.874 | info | Create state lcn.0.S000.M020.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.872 | info | Create state lcn.0.S000.M020.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.870 | info | Create state lcn.0.S000.M020.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.866 | info | Create state lcn.0.S000.M015.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.818 | info | Create state lcn.0.S000.M015.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.814 | info | Create state lcn.0.S000.M015.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.809 | info | Create state lcn.0.S000.M015.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.802 | info | Create state lcn.0.S000.M015.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.756 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:13.755 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:13.754 | debug | [CONN] Changing state: WAIT_RESPONSE => READY
lcn.0 | 2023-02-02 20:23:13.751 | debug | [CONN] Changing state: READY => WAIT_RESPONSE
lcn.0 | 2023-02-02 20:23:13.750 | debug | [CONN] Changing state: WAIT_CONNECTED => READY
lcn.0 | 2023-02-02 20:23:13.749 | info | Create state lcn.0.S000.M015.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.742 | info | Create state lcn.0.S000.M010.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.737 | info | Create state lcn.0.S000.M010.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.733 | info | Create state lcn.0.S000.M010.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.729 | info | Create state lcn.0.S000.M010.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.725 | info | Create state lcn.0.S000.M010.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.722 | info | Create state lcn.0.S000.M010.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.719 | info | Create state lcn.0.S000.M005.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT02
lcn.0 | 2023-02-02 20:23:13.715 | info | Create state lcn.0.S000.M005.REGULATOR_LOCK_OUTS.REGULATOR_LOCK_OUT01
lcn.0 | 2023-02-02 20:23:13.712 | info | Create state lcn.0.S000.M005.REGULATOR_LOCK_OUTS
lcn.0 | 2023-02-02 20:23:13.709 | info | Create state lcn.0.S000.M005.REGULATOR_OUTS.REGULATOR_OUT02
lcn.0 | 2023-02-02 20:23:13.708 | debug | [CONN] Changing state: WAIT_AUTH_OK => WAIT_CONNECTED
lcn.0 | 2023-02-02 20:23:13.707 | debug | [CONN] Changing state: WAIT_PASS => WAIT_AUTH_OK
lcn.0 | 2023-02-02 20:23:13.705 | debug | [CONN] Changing state: WAIT_USER => WAIT_PASS
lcn.0 | 2023-02-02 20:23:13.700 | info | Create state lcn.0.S000.M005.REGULATOR_OUTS.REGULATOR_OUT01
lcn.0 | 2023-02-02 20:23:13.696 | debug | [CONN] Changing state: WAIT_PROMPT => WAIT_USER
lcn.0 | 2023-02-02 20:23:13.693 | debug | [CONN] Changing state: CONNECTING => WAIT_PROMPT
lcn.0 | 2023-02-02 20:23:13.689 | info | Create state lcn.0.S000.M005.REGULATOR_OUTS
lcn.0 | 2023-02-02 20:23:13.495 | info | Found license with 20000 modules
lcn.0 | 2023-02-02 20:23:13.367 | debug | [main] start
lcn.0 | 2023-02-02 20:23:13.348 | info | starting. Version 1.1.1 in /opt/iobroker/node_modules/iobroker.lcn, node: v16.19.0, js-controller: 4.0.24


</body>
</html>

Im PCHK Monitor wird folgendes ausgegeben:
20:27:27 [PCHK] Verbindung zum Bus getrennt
20:27:30 [PCHK] Session error: Start failed - I/O timeout! (Code: 0))
20:27:35 [PCHK] !OM0P

20:27:35 [PCHK] (0..50-mode percent)

20:27:35 [PCHK] !CHD

20:27:35 [PCHK] (dec-mode)

20:27:37 [PCHK] Bus-Verbunden
20:27:47 [PCHK] S000_M201 to M203 Set 0
20:27:55 [PCHK] S000_M025 to M101 Measured value: 2050
20:27:55 [PCHK] S000_M101 statusL Var2/R1Var: 1023
20:27:55 [PCHK] %M000101.A00201023

20:27:59 [PCHK] !OM0P

20:27:59 [PCHK] (0..50-mode percent)

20:27:59 [PCHK] !CHD

20:27:59 [PCHK] (dec-mode)

**Comment by MatthiasUlrich84** [comment]
Ich habe nun den Adapter wieder zum laufen gebracht. Folgendes hat geholfen:

Adapter löschen
Über console eine alte Version des Adapters installiert
iobroker install lcn@0.6.3

Dann über Console upgraden
iobroker upgrade lcn@1.1.1

Danach hat alles funktioniert.

Es scheint hier wirklich ein Problem mit der Installation des Adapters zu geben.
Vielleicht könnt ihr euch das ja mal ansehen.

Danke!

**Comment by Apollon77** [comment]
Ok, istes jetzt gelöst?

**Comment by MatthiasUlrich84** [comment]
Ja es ist in diesem Fall gelöst, es bleibt ein Mysterium. 😉
