### ISSUE TITLE
[gelöst] unbekannte Warnmeldung aus dem lcn-bus jede 30 minuten

### ISSUE THREAD

**Issue by LCNJoe** [ioBroker/ioBroker.lcn#24]
über den LCN-Adapter kommt jede 30 Minuten folgenden Warnung:

Unknown update: {"segment":0,"module":180,"type":"SUM","status":0,"input":"1000"}

Die Meldung kann nicht unterdrückt oder bearbeitet werden. M180 ist die Wetterstation WIH. Mit verschiedenen Werten der WIH werden Summen gebildet für Steuerungen (Raffstoren). Vermutlich kommt daher die Meldung. Alle anderen "üblichen" Funktionen, die auch andere Module haben, funktionieren.

Ist das ein Bug, oder ist die WIH noch zu neu bzw. selten am iobroker in Nutzung?
Wenn ich als Tester für weitere Funktionen beitragen kann, gerne. Habe die Parametriersoftware LCN-Pro.

Gibt es noch Informationen, die ich zur Fehlersuche beitragen kann?

**Comment by MatthiasUlrich84** [comment]
Hallo LCNJoe,

das liegt wahrscheinlich daran, dass der Adapter keine Summen kennt. Diese Telaegramme sind noch nicht integriert. 
Daher kann er das Telegramm nicht deuten.

**Comment by LCNJoe** [comment]
Hallo Matthias,

danke für den Hinweis,

gibt es eine Möglichkeit, die Warnungen im Adapter abzustellen, bis die Summen verarbeitet werden können?
Es ist nicht cool, wenn das Protokoll ständig mit Meldungen vollläuft.

Die Meldungen werden im LCN Bus wohl von anderen Modulen genutzt, da kann man die nicht unterdrücken.
Z.B. der Sonnenstand in Kombination mit der Außen-Temperatur für Rollladen an der Westseite. Die fahren im Sommer über 28°  automatisch runter bevor die Sonne hereinscheint.

**Comment by Apollon77** [comment]
leider ist nicht ersichtlich in elchem Loglevel das geloggt wird aber Du kannst das Loglevel höher setzen der instanz

**Comment by LCNJoe** [comment]
hab nach der Einstellung gesucht und einen Hinweis gefunden:
Instanzen => Expertenmodus an => loglevel pro Adapter einstellen (Info, warm, error, debug, silly)

ein Reiter loglevel finde ich nicht, wo kann der hingekommen sein?

**Comment by Apollon77** [comment]
instanz aufklappen um die es geht

**Comment by LCNJoe** [comment]
ja, hatte ich. 
Hab es jetzt auch gefunden, sorry. Der runde Info Button in der Mitte verbirgt die Einstellung.
