### ISSUE TITLE
LCN-Adapter - Node.js fehler

### ISSUE THREAD

**Issue by teamworkdigital** [ioBroker/ioBroker.lcn#28]
Hallo, seit dem letzten Update auf Node.js v18.20.4 funktioniert der Adapter nicht mehr. Wird dieser noch weiterentwickelt? Wäre echt schade darum diese Möglichkeit nicht mehr zu haben. Würde gerne auch in der Weiterentwicklung unterstützen wenn gewünscht.
Gruß Markus
@GermanBluefox

**Comment by Apollon77** [comment]
"funktioniert nicht mehr" ist jetzt nicht gerade eine ausführliche Fehlerbeschreibung :-) Was sagt denn das Log?

**Comment by teamworkdigital** [comment]
<html>
<body>

host.raspberrypi | 2024-08-02 17:21:50.814 | error | instance system.adapter.lcn.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2024-08-02 17:21:50.813 | error | Caught by controller[0]: Node.js v18.20.4
host.raspberrypi | 2024-08-02 17:21:50.813 | error | Caught by controller[0]: }
host.raspberrypi | 2024-08-02 17:21:50.813 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.lcn/main.js' ]
host.raspberrypi | 2024-08-02 17:21:50.813 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2024-08-02 17:21:50.812 | error | Caught by controller[0]: at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3919) {
host.raspberrypi | 2024-08-02 17:21:50.812 | error | Caught by controller[0]: at 7.fs (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151514)
host.raspberrypi | 2024-08-02 17:21:50.812 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151487)
host.raspberrypi | 2024-08-02 17:21:50.812 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151272)
host.raspberrypi | 2024-08-02 17:21:50.812 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:4026
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3613)
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: at require (node:internal/modules/helpers:177:18)
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1231:19)
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:981:27)
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.lcn/main.js
host.raspberrypi | 2024-08-02 17:21:50.811 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2024-08-02 17:21:50.810 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/build/lib/adapter.js'
host.raspberrypi | 2024-08-02 17:21:50.810 | error | Caught by controller[0]: ^
host.raspberrypi | 2024-08-02 17:21:50.810 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2024-08-02 17:21:50.810 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1143


</body>
</html>

**Comment by Sefina-DS** [comment]
Hi zusammen,

Bei mir ein ähnliches Problem.
Ich habe alles heute auf dem neusten stand gebracht und nun geht der LCN Adapter nicht.
Anbei meine Logs ....

<html><body>

host.IO-Broker | 2024-08-03 21:54:40.301 | info | Rebuild  for adapter system.adapter.lcn.0 not successful in 3 tries. Adapter  will not be restarted again. Please execute "npm install --production"  in adapter directory manually.
-- | -- | -- | --
host.IO-Broker | 2024-08-03 21:54:40.301 | error | instance system.adapter.lcn.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Node.js v20.16.0
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: }
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.lcn/main.js' ]
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3919) {
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at 7.fs (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151514)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151487)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151272)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:4026
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3613)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at require (node:internal/modules/helpers:179:18)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:986:27)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.lcn/main.js
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Require stack:
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/build/lib/adapter.js'
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   ^
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   throw err;
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1148
host.IO-Broker | 2024-08-03 21:54:40.166 | info | instance system.adapter.lcn.0 in version "1.1.8" started with pid 817815
host.IO-Broker | 2024-08-03 21:54:39.965 | info | "system.adapter.lcn.0" enabled
host.IO-Broker | 2024-08-03 21:54:20.246 | info | "system.adapter.lcn.0" disabled


</body>
</html>

**Comment by RicoSpohn** [comment]
Hallo Zusammen, 
ich habe das selbe Problem nach dem Update meines Systems. 
Der LCN Adapter startet nicht mehr.
Auch eine Neuinstallation der Instanz und des Adapters hat nicht geholfen.
Der Fehler trat auf nach dem Update vom Host von 5.0.19 auf 6.0.9 und dem Update der Admin-Instanz auf 7.0.22

Anbei meine Logdatei:

2024-08-04 18:59:42.543 - info: host.xxx() instance system.adapter.lcn.0 in version "1.1.8" started with pid 11312
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]: node:internal/modules/cjs/loader:1205
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]: throw err;
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]: ^
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]:
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]: Error: Cannot find module 'C:/Program Files/iobroker/node_modules/iobroker.js-controller/build/lib/adapter.js'
2024-08-04 18:59:43.996 - error: host.xxx() Caught by controller[0]: Require stack:
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: - C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1202:15)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1027:27)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1290:19)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at require (node:internal/modules/helpers:188:18)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at _0x2b3b62 (C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:3613)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:4026
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at Object. (C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:151272)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at Object. (C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:151487)
2024-08-04 18:59:43.997 - error: host.xxx() Caught by controller[0]: at 7.fs (C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:151514)
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: at _0x2b3b62 (C:\Program Files\iobroker\node_modules\iobroker.lcn\main.js:1:3919) {
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: requireStack: [
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: 'C:\\Program Files\\iobroker\\node_modules\\iobroker.lcn\\main.js'
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: ]
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: }
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]:
2024-08-04 18:59:43.998 - error: host.xxx() Caught by controller[0]: Node.js v22.0.0
2024-08-04 18:59:43.998 - error: host.xxx() instance system.adapter.lcn.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-08-04 18:59:43.999 - info: host.xxx() Rebuild for adapter system.adapter.lcn.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.

**Comment by Apollon77** [comment]
presumable there is an too old version of adapter-core used and needs to be updated @GermanBluefox

**Comment by GermanBluefox** [comment]
Please try 2.0.0

**Comment by teamworkdigital** [comment]
Hallo, danke für das Update, aber jetzt startet der Adapter gar nicht mehr und die Einstellungen kann man nicht mehr aufrufen.
Es erscheint beigefügte Fehlerseite.
![ioBroker_LCN_Einstellungen](https://github.com/user-attachments/assets/f44415a3-7db0-4201-92ce-2576b890309c)

**Comment by Sefina-DS** [comment]
Hallo, 

Ich habe natürlich die Version 1.2.0 versucht zu installieren.
Mit der Version 2.0.0 funktioniert es, musste da ich den Adapter komplett gelöscht habe die Module noch einscannen.

MfG

**Comment by Sefina-DS** [comment]
> Hallo @GermanBluefox , danke für das Update, aber jetzt startet der Adapter gar nicht mehr und die Einstellungen kann man nicht mehr aufrufen. Es erscheint beigefügte Fehlerseite. ![ioBroker_LCN_Einstellungen](https://private-user-images.githubusercontent.com/85923979/355320470-f44415a3-7db0-4201-92ce-2576b890309c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjMwNzUsIm5iZiI6MTcyMjkyMjc3NSwicGF0aCI6Ii84NTkyMzk3OS8zNTUzMjA0NzAtZjQ0NDE1YTMtN2RiMC00MjAxLTkyY2UtMjU3NmI4OTAzMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA1MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNGY2MGU5NDAxMDhjZjc4ZTAyNzVkOWFjZmY1Nzg3M2FlNTUwM2Q4MjBlYmZiZTg4OTIwNzQ1NzdjMmRjYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6p5g9tVmimjBiHtGlSxbnyztXz4w_TSMk9LyDgmlayU)
> 
> host.raspberrypi | 2024-08-06 07:19:36.997 | error | startInstance lcn.0: cannot find start file! host.raspberrypi | 2024-08-06 07:19:35.477 | info | "system.adapter.lcn.0" enabled

Ich würde den Adapter komplett deinstallieren, dann installieren, dann auf Version 2.0.0 updaten, Module neu einlesen.

**Comment by teamworkdigital** [comment]
Danke @Sefina-DS. Das habe ich schon getestet. Alles deinstalliert und neu drauf. Leider immer noch das gleiche Problem.
@GermanBluefox

**Comment by RicoSpohn** [comment]
Hallo @GermanBluefox, danke für deine Mühen, ich habe den Adapter 2.0.0 auf einem Windows System installiert. Leider auch ohne Erfolg. (Fehler 404 und keine Einstellungen möglich.)
Gibt es eine Möglichkeit den Host auf eine ältere Version zurückzusetzen, damit der Adapter wieder läuft? Ich habe relativ viele Abhängigkeiten in meinem Haus programmiert und bin auf den Adapter angewiesen.
mfg

**Comment by Apollon77** [comment]
Nur ummsicherzugehen: 2.0.0 normal übers latest repo oder v0n npm installiert? NICHT von Github!!!

**Comment by teamworkdigital** [comment]
OH-Mann. Hatte es von GitHub, da es in der npm nicht größer 1.1.8 war. Heute mit de2.0.0 über npm funktioniert wieder alles. DANKE @Apollon77 & @GermanBluefox !!!!! TOP Service!
