### ISSUE TITLE
Variablen output

### ISSUE THREAD

**Issue by mangel8** [ioBroker/ioBroker.lcn#8]
Wünsche einen schönen guten Tag,

ich wollte fragen ob es mölich wäre Variablen aus dem IO-Broker an LCN Module zu senden. Ich möchte beispielsweise die Ausßentemperatur oder Windgeschwindigkeit von einer Wetterstation oder die ZigBee Fensterkontakte an den Displays im LCN Bus anzeigen lassen oder die Signale zur Steuerung verwenden.

Vielen Dank

**Comment by MatthiasUlrich84** [comment]
Hallo mangel8,

Das senden von Außerhalb auf Variablen im Bus sieht LCN nicht vor. Du kannst jedoch abhängig von den Geräten per Script ein virtuelles Relais schalten lassen. Da kannst du den Status im Display als Icon anzeigen lassen. 

Es gibt neuerdings eine Funktion zum Senden von dynamischem Text an Displays. 
dafür musst du mit der Pro die entsprechende Zeile als dyn Text einstellen. Dann kamnst du den Datenpung Display Output der jeweiligen Zeile senden. In 1.0.2 gehen nur 10 Zeichen. 
ab 1.0.4 gehen 4x12 Zeichen. Allerdings macht diese Version noch Probleme mit Variablen bei mir. 

Gruß Matthias.

**Comment by mangel8** [comment]
Hallo Matthias,

danke für die Information das versuche ich heute nachmittag. Wenn das so klappt wären damit meine Probleme gelöst,

Grüße Michael
